apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
  namespace: default
spec:
  secretName: wisecow-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: wisecow.local
  dnsNames:
    - wisecow.local
#This defines what certificate I want for wisecow.local.
