name: CI/CD for wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GCSHUBHAM_DOCKERHUB }}
          password: ${{ secrets.gcshubham }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.GCSHUBHAM_DOCKERHUB }}/wisecow:${{ github.sha }} .
          docker push ${{ secrets.GCSHUBHAM_DOCKERHUB }}/wisecow:${{ github.sha }}

      - name: Deploy to Minikube
        run: |
          sed -i "s|image: .*|image: ${{ secrets.GCSHUBHAM_DOCKERHUB }}/wisecow:${{ github.sha }}|" k8s/wisecow-deployment.yaml
          kubectl apply -f k8s/wisecow-deployment.yaml
          kubectl apply -f k8s/wisecow-service.yaml
          kubectl apply -f k8s/wisecow-ingress.yaml
