name: AccuKnox Complete Security Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # ------------------------------------------------
  # ðŸ”¹ 1. AccuKnox DAST Scan
  # ------------------------------------------------
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AccuKnox DAST Scan
        uses: accuknox/dast-scan-action@v1.0.1
        with:
          target_url: "http://testphp.vulnweb.com"
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          severity_threshold: "HIGH"
          dast_scan_type: "full-scan"

  # ------------------------------------------------
  # ðŸ”¹ 2. AccuKnox Secret Scan
  # ------------------------------------------------
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Secret Scan
        uses: accuknox/secret-scan-action@v0.0.1
        with:
          branch: "main"
          results: ""
          exclude_paths: "tests/,docs/"
          additional_arguments: ""
          base_command: ""
          output_format: json
          output_file_path: "./secret_results.json"
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          soft_fail: true

  # ------------------------------------------------
  # ðŸ”¹ 3. AccuKnox Container Scan
  # ------------------------------------------------
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AccuKnox Container Scanner
        uses: accuknox/container-scan-action@v1.0.1
        with:
          soft_fail: false
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          image: "your-image-name"
          tag: "latest"
          severity: "LOW, MEDIUM, HIGH, CRITICAL, UNKNOWN"

  # ------------------------------------------------
  # ðŸ”¹ 4. AccuKnox IaC Scan
  # ------------------------------------------------
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run IaC scan
        uses: accuknox/iac-scan-action@v1.0.1
        with:
          directory: "."
          compact: true
          quiet: true
          output_format: json
          output_file_path: "./results.json"
          soft_fail: true
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
